name: auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dashboard: ^0.0.3+1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  intl: ^0.19.0
  carousel_slider: ^4.0.0
  iconsax: ^0.0.8
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  persistent_shopping_cart: ^0.0.7
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  marquee: ^2.2.3
  image_picker: ^1.0.0
  flutter_easyloading: ^3.0.5
  comment_box: ^0.0.18
  firebase_storage: ^11.6.9
  url_launcher: ^6.0.20
  flutter:
    sdk: flutter
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/  
